DELETE http://localhost:8080/events/2/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTc0MjA4MDM0MiwidXNlcklkIjoyfQ._OIQHokkE8qNeuMYCiHTgBa1skQayy1LFKL-CRiNX9w